import {
  createDataTableConfig,
  DataTable,
  type DataTableLocale,
} from '../index';

interface User {
  id: string;
  name: string;
  email: string;
  age: number;
  department: 'Engineering' | 'Product' | 'Support';
  region: 'North' | 'South' | 'East' | 'West';
  status: boolean;
  birthDate: string;
  createdAt: string;
}

const userTableConfig = createDataTableConfig<User>({
  columns: {
    name: {
      enableExport: true,
      enableGrouping: false,
      header: 'Name',
      label: 'Full Name',
      maxSize: 280,
      size: 180,
      type: 'text',
    },
    email: {
      enableExport: true,
      enableGrouping: false,
      header: 'Email',
      label: 'Email Address',
      maxSize: 360,
      size: 240,
      type: 'text',
    },
    department: {
      align: 'center',
      enableExport: true,
      enableGrouping: true,
      header: 'Department',
      maxSize: 220,
      size: 180,
      type: 'select',
    },
    age: {
      enableExport: true,
      enableGrouping: false,
      header: 'Age',
      maxSize: 120,
      size: 120,
      type: 'number',
    },
    region: {
      align: 'center',
      enableExport: true,
      enableGrouping: true,
      header: 'Region',
      maxSize: 180,
      size: 136,
      type: 'multi-select',
    },
    status: {
      enableExport: true,
      enableGrouping: true,
      header: 'Status',
      maxSize: 160,
      size: 140,
      type: 'boolean',
    },
    birthDate: {
      enableExport: true,
      enableGrouping: false,
      header: 'Birth Date',
      maxSize: 220,
      size: 160,
      type: 'date',
    },
    createdAt: {
      enableExport: true,
      enableGrouping: false,
      header: 'Created',
      label: 'Created At',
      maxSize: 220,
      size: 176,
      type: 'date-range',
    },
  },
  defaultViewName: 'Demo view',
  preset: 'enterprise',
  storageKey: 'cereda-table-demo-saved-views',
});

const SAMPLE_USERS: User[] = [
  {
    id: '1',
    name: 'Alice Martin',
    email: 'alice@example.com',
    age: 32,
    department: 'Engineering',
    region: 'North',
    status: true,
    birthDate: '1991-04-12',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Bob Chen',
    email: 'bob@example.com',
    age: 29,
    department: 'Product',
    region: 'South',
    status: false,
    birthDate: '1994-08-27',
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    name: 'Carol Davis',
    email: 'carol@example.com',
    age: 41,
    department: 'Support',
    region: 'West',
    status: true,
    birthDate: '1982-11-03',
    createdAt: '2024-03-10',
  },
  {
    id: '4',
    name: 'Daniel Rivera',
    email: 'daniel@northwind.dev',
    age: 35,
    department: 'Engineering',
    region: 'North',
    status: false,
    birthDate: '1988-06-19',
    createdAt: '2024-04-08',
  },
  {
    id: '5',
    name: 'Erin Patel',
    email: 'erin@studio.example',
    age: 27,
    department: 'Product',
    region: 'South',
    status: true,
    birthDate: '1996-01-23',
    createdAt: '2024-05-18',
  },
  {
    id: '6',
    name: 'Fatima Khan',
    email: 'fatima@contoso.example',
    age: 38,
    department: 'Support',
    region: 'West',
    status: false,
    birthDate: '1985-09-14',
    createdAt: '2024-06-22',
  },
  {
    id: '7',
    name: 'George Lewis',
    email: 'george@acme.example',
    age: 44,
    department: 'Engineering',
    region: 'North',
    status: true,
    birthDate: '1980-03-08',
    createdAt: '2024-07-05',
  },
  {
    id: '8',
    name: 'Hana Suzuki',
    email: 'hana@acme.example',
    age: 31,
    department: 'Product',
    region: 'South',
    status: true,
    birthDate: '1992-12-01',
    createdAt: '2024-08-11',
  },
  {
    id: '9',
    name: 'Ivan Novak',
    email: 'ivan@acme.example',
    age: 36,
    department: 'Support',
    region: 'West',
    status: false,
    birthDate: '1987-07-25',
    createdAt: '2024-09-16',
  },
  {
    id: '10',
    name: 'Jules Moreau',
    email: 'jules@acme.example',
    age: 28,
    department: 'Engineering',
    region: 'North',
    status: false,
    birthDate: '1995-05-17',
    createdAt: '2024-10-03',
  },
  {
    id: '11',
    name: 'Kira Rossi',
    email: 'kira@acme.example',
    age: 45,
    department: 'Product',
    region: 'South',
    status: true,
    birthDate: '1979-10-29',
    createdAt: '2024-11-19',
  },
  {
    id: '12',
    name: 'Liam Carter',
    email: 'liam@acme.example',
    age: 33,
    department: 'Support',
    region: 'West',
    status: true,
    birthDate: '1990-02-14',
    createdAt: '2024-12-07',
  },
  {
    id: '13',
    name: 'Maya Brooks',
    email: 'maya@acme.example',
    age: 30,
    department: 'Engineering',
    region: 'East',
    status: true,
    birthDate: '1993-03-18',
    createdAt: '2025-01-09',
  },
  {
    id: '14',
    name: 'Noah Bennett',
    email: 'noah@acme.example',
    age: 39,
    department: 'Product',
    region: 'East',
    status: false,
    birthDate: '1984-10-04',
    createdAt: '2025-02-13',
  },
  {
    id: '15',
    name: 'Olivia Scott',
    email: 'olivia.scott@vertex.io',
    age: 26,
    department: 'Engineering',
    region: 'West',
    status: true,
    birthDate: '1998-07-11',
    createdAt: '2025-03-01',
  },
  {
    id: '16',
    name: 'Paulo Ferreira',
    email: 'paulo.f@globalco.example',
    age: 43,
    department: 'Support',
    region: 'South',
    status: false,
    birthDate: '1981-02-28',
    createdAt: '2025-03-14',
  },
  {
    id: '17',
    name: 'Quinn Nakamura',
    email: 'quinn@brightlab.dev',
    age: 34,
    department: 'Product',
    region: 'North',
    status: true,
    birthDate: '1990-09-05',
    createdAt: '2025-03-22',
  },
  {
    id: '18',
    name: 'Rachel Okonkwo',
    email: 'rachel.o@nexus.example',
    age: 29,
    department: 'Engineering',
    region: 'East',
    status: true,
    birthDate: '1994-12-19',
    createdAt: '2025-04-03',
  },
  {
    id: '19',
    name: 'Samuel Park',
    email: 'sam.park@coldwave.io',
    age: 37,
    department: 'Support',
    region: 'West',
    status: false,
    birthDate: '1987-05-30',
    createdAt: '2025-04-11',
  },
  {
    id: '20',
    name: 'Talia Hernandez',
    email: 'talia.h@openloop.dev',
    age: 31,
    department: 'Product',
    region: 'South',
    status: true,
    birthDate: '1993-01-07',
    createdAt: '2025-04-18',
  },
  {
    id: '21',
    name: 'Umar Hassan',
    email: 'umar.hassan@stackco.example',
    age: 42,
    department: 'Engineering',
    region: 'North',
    status: false,
    birthDate: '1982-08-23',
    createdAt: '2025-04-25',
  },
  {
    id: '22',
    name: 'Valentina Cruz',
    email: 'val.cruz@softedge.io',
    age: 28,
    department: 'Support',
    region: 'East',
    status: true,
    birthDate: '1996-03-14',
    createdAt: '2025-05-02',
  },
  {
    id: '23',
    name: 'William Osei',
    email: 'w.osei@dataplex.example',
    age: 46,
    department: 'Product',
    region: 'West',
    status: false,
    birthDate: '1978-11-01',
    createdAt: '2025-05-07',
  },
  {
    id: '24',
    name: 'Xiomara Reyes',
    email: 'xiomara@ironvault.dev',
    age: 33,
    department: 'Engineering',
    region: 'South',
    status: true,
    birthDate: '1991-06-17',
    createdAt: '2025-05-10',
  },
  {
    id: '25',
    name: 'Yusuf Lindqvist',
    email: 'yusuf.l@clearpath.io',
    age: 38,
    department: 'Support',
    region: 'North',
    status: true,
    birthDate: '1986-10-09',
    createdAt: '2025-05-12',
  },
  {
    id: '26',
    name: 'Zoe Blackwell',
    email: 'zoe.b@hubstack.example',
    age: 25,
    department: 'Product',
    region: 'East',
    status: false,
    birthDate: '1999-04-22',
    createdAt: '2025-05-14',
  },
  {
    id: '27',
    name: 'Aaron Müller',
    email: 'aaron.m@primelink.dev',
    age: 40,
    department: 'Engineering',
    region: 'West',
    status: true,
    birthDate: '1984-07-03',
    createdAt: '2025-05-15',
  },
  {
    id: '28',
    name: 'Beatrix Andersen',
    email: 'bea.andersen@coreflow.io',
    age: 35,
    department: 'Support',
    region: 'South',
    status: false,
    birthDate: '1989-01-26',
    createdAt: '2025-05-16',
  },
  {
    id: '29',
    name: 'Carlos Mbeki',
    email: 'c.mbeki@axontech.example',
    age: 30,
    department: 'Product',
    region: 'North',
    status: true,
    birthDate: '1994-09-13',
    createdAt: '2025-05-17',
  },
  {
    id: '30',
    name: 'Diana Svensson',
    email: 'diana.sv@loopcraft.dev',
    age: 44,
    department: 'Engineering',
    region: 'East',
    status: false,
    birthDate: '1980-12-08',
    createdAt: '2025-05-18',
  },
];

interface UserTableExampleProps {
  locale?: DataTableLocale;
}

export function UserTableExample({ locale }: UserTableExampleProps) {
  return (
    <DataTable<User>
      data={SAMPLE_USERS}
      {...userTableConfig}
      bodyHeight="60vh"
      enableRowNumbers
      locale={locale}
    />
  );
}
